DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS loans;
DROP TABLE IF EXISTS signers;
DROP TABLE IF EXISTS auth_tokens;

CREATE TABLE signers (
 id SERIAL PRIMARY KEY,
 first_name TEXT NOT NULL,
 last_name TEXT NOT NULL,
 email TEXT UNIQUE NOT NULL
);

CREATE TABLE loans (
 id SERIAL PRIMARY KEY,
 principal_amount NUMERIC(19, 2) NOT NULL,
 fee_amount NUMERIC(19, 2) NOT NULL,
 outstanding_balance NUMERIC(19, 2) NOT NULL,
 signer_ids INTEGER[] NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE payments (
 id SERIAL PRIMARY KEY,
 amount NUMERIC(19, 2) NOT NULL,
 loan_id INTEGER REFERENCES loans(id),
 status TEXT NOT NULL,
 external_payment_id TEXT UNIQUE NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auth_tokens (
 id SERIAL PRIMARY KEY,
 token VARCHAR(100) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);